/**
 * Generated by org.emoflon.gips.build.generator.templates.ObjectiveTemplate
 */
package audiologyoptimiser.api.gips.objective;

import audiologyoptimiser.api.gips.objective.DelayCostV2;
import java.util.List;
import org.emoflon.gips.core.milp.model.LinearFunction;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.core.milp.model.Constant;
import org.emoflon.gips.intermediate.GipsIntermediate.Objective;
import java.util.LinkedList;
import org.emoflon.gips.core.milp.model.Term;
import org.emoflon.gips.core.milp.model.WeightedLinearFunction;
import org.emoflon.gips.core.GipsObjective;
import org.emoflon.gips.core.milp.model.NestedLinearFunction;

public class AudiologyoptimiserGipsObjective extends GipsObjective{
	
	protected DelayCostV2 delayCostV2;
	
	public AudiologyoptimiserGipsObjective(final GipsEngine engine, final Objective objective) {
		super(engine, objective);
	}
	
	@Override
	protected void initLocalObjectives() {
		delayCostV2 = (DelayCostV2) engine.getLinearFunctions().get("delayCostV2");
	}
	
	@Override
	protected void buildTerms() {
		
		weightedFunctions.add(new WeightedLinearFunction(delayCostV2.getLinearFunctionFunction(), 1.0));
		
	}
	
}
