/**
 * Generated by org.emoflon.gips.build.generator.templates.function.MappingFunctionTemplate
 */
package audiologyoptimiser.api.gips.objective;

import audiologyoptimiser.api.gips.mapping.AssignApptMapping;
import java.util.List;
import org.emoflon.gips.intermediate.GipsIntermediate.MappingFunction;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.core.milp.model.Constant;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import org.emoflon.gips.core.GipsMappingLinearFunction;
import java.util.LinkedList;
import org.emoflon.gips.core.milp.model.Term;

public class DelayCostV2 extends GipsMappingLinearFunction<AudiologyoptimiserGipsAPI, AssignApptMapping>{
	public DelayCostV2(final AudiologyoptimiserGipsAPI engine, final MappingFunction function) {
		super(engine, function);
	}
	
	@Override
	protected void buildTerms(final AssignApptMapping context) {
		
		terms.add(new Term(context, builder_0(context)));
	}
	
	protected double builder_0(final AssignApptMapping context) {
		return (context.getPlanningDay().getDayIndex() + (-1.0) * (context.getRequest().getIdealDayIndex())) * (1.0);
	}
	
}
