/**
 * Generated by org.emoflon.gips.build.generator.templates.constraint.MappingConstraintTemplate
 */
package audiologyoptimiser.api.gips.constraint;

import audiologyoptimiser.api.gips.mapping.AssignApptMapping;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.core.milp.model.Constraint;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import org.emoflon.gips.core.GipsMappingConstraint;
import java.util.Set;
import org.emoflon.gips.intermediate.GipsIntermediate.MappingConstraint;
import org.emoflon.gips.core.milp.model.Term;
import java.util.stream.Collectors;
import org.emoflon.gips.core.GlobalMappingIndexer;
import java.util.List;
import audiologyoptimiser.api.gips.mapping.RoomUsedByStaffMapping;
import org.emoflon.gips.core.MappingIndexer;
import org.emoflon.gips.core.GipsMapper;
import java.util.LinkedList;
import java.util.Collections;

public class MappingConstraint3OnroomUsedByStaff extends GipsMappingConstraint<AudiologyoptimiserGipsAPI, RoomUsedByStaffMapping>{
	
	public MappingConstraint3OnroomUsedByStaff(final AudiologyoptimiserGipsAPI engine, final MappingConstraint constraint) {
		super(engine, constraint);
	}
	
	@Override
	protected double buildConstantRhs(final RoomUsedByStaffMapping context) {
		return 0.0;
	}
		
	@Override
	protected List<Term> buildVariableLhs(final RoomUsedByStaffMapping context) {
		List<Term> terms = Collections.synchronizedList(new LinkedList<>());
		builder_0(terms, context);
		terms.add(new Term(context, builder_1(context)));
		return terms;
	}
	
	@Override
	protected double buildConstantLhs(final RoomUsedByStaffMapping context) {
		throw new UnsupportedOperationException("Constraint has an LHS that contains (M)ILP variables.");
	}
	
	@Override
	protected boolean buildConstantExpression(final RoomUsedByStaffMapping context) {
		throw new UnsupportedOperationException("Constraint has no constant boolean expression.");
	}
		
	@Override
	protected List<Constraint> buildAdditionalConstraints(final RoomUsedByStaffMapping context) {
		throw new UnsupportedOperationException("Constraint has no depending or substitute constraints.");
	}
	protected double builder_1(final RoomUsedByStaffMapping context) {
		return (-1.0) * (1.0);
	}
	protected void builder_0(final List<Term> terms, final RoomUsedByStaffMapping context) {
		// Mapping Indexer
		final GipsMapper<?> mapper = engine.getMapper("assignAppt");
		final GlobalMappingIndexer globalIndexer = GlobalMappingIndexer.getInstance();
		globalIndexer.createIndexer(mapper);
		final MappingIndexer indexer = globalIndexer.getIndexer(mapper);
		indexer.initIfNecessary(mapper, Set.of("request", "staffMember", "planningWeek", "planningDay", "room"));
		indexer.getMappingsOfNodes(Set.of(context.getStaffMember(), context.getRoom(), context.getPlanningDay())).parallelStream()
		.map(mapping -> (AssignApptMapping) mapping)
		.filter(elt -> elt.getStaffMember().equals(context.getStaffMember()) && elt.getRoom().equals(context.getRoom()) && elt.getPlanningDay().equals(context.getPlanningDay()))
		.forEach(elt -> {
			terms.add(new Term(elt, (double) 1.0));
		});
	}
}
