/**
 * Generated by org.emoflon.gips.build.generator.templates.constraint.PatternConstraintTemplate
 */
package audiologyoptimiser.api.gips.constraint;

import audiologyoptimiser.api.gips.mapping.AssignApptMapping;
import org.emoflon.gips.intermediate.GipsIntermediate.PatternConstraint;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.core.milp.model.Constraint;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import org.emoflon.gips.core.gt.GipsPatternConstraint;
import java.util.Set;
import org.emoflon.gips.core.milp.model.Term;
import java.util.stream.Collectors;
import org.emoflon.gips.core.GlobalMappingIndexer;
import java.util.List;
import org.emoflon.gips.core.MappingIndexer;
import org.emoflon.gips.core.GipsMapper;
import audiologyoptimiser.api.rules.StaffWeekTuplePattern;
import audiologyoptimiser.api.matches.StaffWeekTupleMatch;
import java.util.LinkedList;
import java.util.Collections;

public class PatternConstraint6OnstaffWeekTuple extends GipsPatternConstraint<AudiologyoptimiserGipsAPI, StaffWeekTupleMatch, StaffWeekTuplePattern>{
	
	public PatternConstraint6OnstaffWeekTuple(final AudiologyoptimiserGipsAPI engine, final PatternConstraint constraint, final StaffWeekTuplePattern pattern) {
		super(engine, constraint, pattern);
	}
	
	@Override
	protected double buildConstantRhs(final StaffWeekTupleMatch context) {
		return (context.getStaffMember().getWeeklyHours()) * (60);
	}
		
	@Override
	protected List<Term> buildVariableLhs(final StaffWeekTupleMatch context) {
		List<Term> terms = Collections.synchronizedList(new LinkedList<>());
		builder_0(terms, context);
		return terms;
	}
	
	@Override
	protected double buildConstantLhs(final StaffWeekTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has an LHS that contains (M)ILP variables.");
	}
	
	@Override
	protected boolean buildConstantExpression(final StaffWeekTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has no constant boolean expression.");
	}
		
	@Override
	protected List<Constraint> buildAdditionalConstraints(final StaffWeekTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has no depending or substitute constraints.");
	}
	protected void builder_0(final List<Term> terms, final StaffWeekTupleMatch context) {
		// Mapping Indexer
		final GipsMapper<?> mapper = engine.getMapper("assignAppt");
		final GlobalMappingIndexer globalIndexer = GlobalMappingIndexer.getInstance();
		globalIndexer.createIndexer(mapper);
		final MappingIndexer indexer = globalIndexer.getIndexer(mapper);
		indexer.initIfNecessary(mapper, Set.of("request", "staffMember", "planningWeek", "planningDay", "room"));
		indexer.getMappingsOfNodes(Set.of(context.getStaffMember(), context.getPlanningWeek())).parallelStream()
		.map(mapping -> (AssignApptMapping) mapping)
		.filter(elt -> elt.getStaffMember().equals(context.getStaffMember()) && elt.getPlanningWeek().equals(context.getPlanningWeek()))
		.forEach(elt -> {
			terms.add(new Term(elt, (double) ((elt.getRequest().getDurationSlots()) * (15)) * (1.0)));
		});
	}
}
