/**
 * Generated by org.emoflon.gips.build.generator.templates.constraint.PatternConstraintTemplate
 */
package audiologyoptimiser.api.gips.constraint;

import audiologyoptimiser.api.gips.mapping.AssignApptMapping;
import org.emoflon.gips.intermediate.GipsIntermediate.PatternConstraint;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.core.milp.model.Constraint;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import audiologyoptimiser.api.matches.RoomDaySlotTupleMatch;
import org.emoflon.gips.core.gt.GipsPatternConstraint;
import java.util.Set;
import org.emoflon.gips.core.milp.model.Term;
import java.util.stream.Collectors;
import org.emoflon.gips.core.GlobalMappingIndexer;
import java.util.List;
import org.emoflon.gips.core.MappingIndexer;
import org.emoflon.gips.core.GipsMapper;
import java.util.LinkedList;
import java.util.Collections;
import audiologyoptimiser.api.rules.RoomDaySlotTuplePattern;

public class PatternConstraint2OnroomDaySlotTuple extends GipsPatternConstraint<AudiologyoptimiserGipsAPI, RoomDaySlotTupleMatch, RoomDaySlotTuplePattern>{
	
	public PatternConstraint2OnroomDaySlotTuple(final AudiologyoptimiserGipsAPI engine, final PatternConstraint constraint, final RoomDaySlotTuplePattern pattern) {
		super(engine, constraint, pattern);
	}
	
	@Override
	protected double buildConstantRhs(final RoomDaySlotTupleMatch context) {
		return 1;
	}
		
	@Override
	protected List<Term> buildVariableLhs(final RoomDaySlotTupleMatch context) {
		List<Term> terms = Collections.synchronizedList(new LinkedList<>());
		builder_0(terms, context);
		return terms;
	}
	
	@Override
	protected double buildConstantLhs(final RoomDaySlotTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has an LHS that contains (M)ILP variables.");
	}
	
	@Override
	protected boolean buildConstantExpression(final RoomDaySlotTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has no constant boolean expression.");
	}
		
	@Override
	protected List<Constraint> buildAdditionalConstraints(final RoomDaySlotTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has no depending or substitute constraints.");
	}
	protected void builder_0(final List<Term> terms, final RoomDaySlotTupleMatch context) {
		// Mapping Indexer
		final GipsMapper<?> mapper = engine.getMapper("assignAppt");
		final GlobalMappingIndexer globalIndexer = GlobalMappingIndexer.getInstance();
		globalIndexer.createIndexer(mapper);
		final MappingIndexer indexer = globalIndexer.getIndexer(mapper);
		indexer.initIfNecessary(mapper, Set.of("request", "staffMember", "planningWeek", "planningDay", "room"));
		indexer.getMappingsOfNodes(Set.of(context.getRoom(), context.getPlanningDay())).parallelStream()
		.map(mapping -> (AssignApptMapping) mapping)
		.filter(elt -> elt.getRoom().equals(context.getRoom()) && elt.getPlanningDay().equals(context.getPlanningDay()) && elt.getStartSlot().getStartIndex() < context.getInterval().getStartIndex() && context.getInterval().getStartIndex() < elt.getStartSlot().getStartIndex() + elt.getRequest().getDurationSlots())
		.forEach(elt -> {
			terms.add(new Term(elt, (double) 1.0));
		});
	}
}
