/**
 * Generated by org.emoflon.gips.build.generator.templates.constraint.PatternConstraintTemplate
 */
package audiologyoptimiser.api.gips.constraint;

import org.emoflon.gips.intermediate.GipsIntermediate.PatternConstraint;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.core.milp.model.Constraint;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import org.emoflon.gips.core.gt.GipsPatternConstraint;
import java.util.Set;
import org.emoflon.gips.core.milp.model.Term;
import audiologyoptimiser.api.rules.StaffDayTuplePattern;
import java.util.stream.Collectors;
import org.emoflon.gips.core.GlobalMappingIndexer;
import java.util.List;
import audiologyoptimiser.api.gips.mapping.RoomUsedByStaffMapping;
import org.emoflon.gips.core.MappingIndexer;
import org.emoflon.gips.core.GipsMapper;
import audiologyoptimiser.api.matches.StaffDayTupleMatch;
import java.util.LinkedList;
import java.util.Collections;

public class PatternConstraint5OnstaffDayTuple extends GipsPatternConstraint<AudiologyoptimiserGipsAPI, StaffDayTupleMatch, StaffDayTuplePattern>{
	
	public PatternConstraint5OnstaffDayTuple(final AudiologyoptimiserGipsAPI engine, final PatternConstraint constraint, final StaffDayTuplePattern pattern) {
		super(engine, constraint, pattern);
	}
	
	@Override
	protected double buildConstantRhs(final StaffDayTupleMatch context) {
		return 1;
	}
		
	@Override
	protected List<Term> buildVariableLhs(final StaffDayTupleMatch context) {
		List<Term> terms = Collections.synchronizedList(new LinkedList<>());
		builder_0(terms, context);
		return terms;
	}
	
	@Override
	protected double buildConstantLhs(final StaffDayTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has an LHS that contains (M)ILP variables.");
	}
	
	@Override
	protected boolean buildConstantExpression(final StaffDayTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has no constant boolean expression.");
	}
		
	@Override
	protected List<Constraint> buildAdditionalConstraints(final StaffDayTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has no depending or substitute constraints.");
	}
	protected void builder_0(final List<Term> terms, final StaffDayTupleMatch context) {
		// Mapping Indexer
		final GipsMapper<?> mapper = engine.getMapper("roomUsedByStaff");
		final GlobalMappingIndexer globalIndexer = GlobalMappingIndexer.getInstance();
		globalIndexer.createIndexer(mapper);
		final MappingIndexer indexer = globalIndexer.getIndexer(mapper);
		indexer.initIfNecessary(mapper, Set.of("staffMember", "planningDay"));
		indexer.getMappingsOfNodes(Set.of(context.getStaffMember(), context.getPlanningDay())).parallelStream()
		.map(mapping -> (RoomUsedByStaffMapping) mapping)
		.filter(elt -> elt.getStaffMember().equals(context.getStaffMember()) && elt.getPlanningDay().equals(context.getPlanningDay()))
		.forEach(elt -> {
			terms.add(new Term(elt, (double) 1.0));
		});
	}
}
