/**
 * Generated by org.emoflon.gips.build.generator.templates.constraint.PatternConstraintTemplate
 */
package audiologyoptimiser.api.gips.constraint;

import audiologyoptimiser.api.gips.mapping.AssignApptMapping;
import org.emoflon.gips.intermediate.GipsIntermediate.PatternConstraint;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.core.milp.model.Constraint;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import org.emoflon.gips.core.gt.GipsPatternConstraint;
import java.util.Set;
import org.emoflon.gips.core.milp.model.Term;
import java.util.stream.Collectors;
import org.emoflon.gips.core.GlobalMappingIndexer;
import audiologyoptimiser.api.matches.RequestTupleMatch;
import java.util.List;
import org.emoflon.gips.core.MappingIndexer;
import org.emoflon.gips.core.GipsMapper;
import audiologyoptimiser.api.rules.RequestTuplePattern;
import java.util.LinkedList;
import java.util.Collections;

public class PatternConstraint0OnrequestTuple extends GipsPatternConstraint<AudiologyoptimiserGipsAPI, RequestTupleMatch, RequestTuplePattern>{
	
	public PatternConstraint0OnrequestTuple(final AudiologyoptimiserGipsAPI engine, final PatternConstraint constraint, final RequestTuplePattern pattern) {
		super(engine, constraint, pattern);
	}
	
	@Override
	protected double buildConstantRhs(final RequestTupleMatch context) {
		return 1;
	}
		
	@Override
	protected List<Term> buildVariableLhs(final RequestTupleMatch context) {
		List<Term> terms = Collections.synchronizedList(new LinkedList<>());
		builder_0(terms, context);
		return terms;
	}
	
	@Override
	protected double buildConstantLhs(final RequestTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has an LHS that contains (M)ILP variables.");
	}
	
	@Override
	protected boolean buildConstantExpression(final RequestTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has no constant boolean expression.");
	}
		
	@Override
	protected List<Constraint> buildAdditionalConstraints(final RequestTupleMatch context) {
		throw new UnsupportedOperationException("Constraint has no depending or substitute constraints.");
	}
	protected void builder_0(final List<Term> terms, final RequestTupleMatch context) {
		// Mapping Indexer
		final GipsMapper<?> mapper = engine.getMapper("assignAppt");
		final GlobalMappingIndexer globalIndexer = GlobalMappingIndexer.getInstance();
		globalIndexer.createIndexer(mapper);
		final MappingIndexer indexer = globalIndexer.getIndexer(mapper);
		indexer.initIfNecessary(mapper, Set.of("request", "staffMember", "planningWeek", "planningDay", "room"));
		indexer.getMappingsOfNodes(Set.of(context.getRequest())).parallelStream()
		.map(mapping -> (AssignApptMapping) mapping)
		.filter(elt -> elt.getRequest().equals(context.getRequest()))
		.forEach(elt -> {
			terms.add(new Term(elt, (double) 1.0));
		});
	}
}
