/**
 * Generated by org.emoflon.gips.build.generator.templates.RuleMapperTemplate
 */
package audiologyoptimiser.api.gips.mapper;

import audiologyoptimiser.api.AudiologyoptimiserAPI;
import audiologyoptimiser.api.gips.mapping.AssignApptMapping;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.intermediate.GipsIntermediate.Mapping;
import org.emoflon.gips.core.gt.GipsRuleMapper;
import audiologyoptimiser.api.matches.AssignAppointmentMatch;
import audiologyoptimiser.api.rules.AssignAppointmentRule;

public class AssignApptMapper extends GipsRuleMapper<AssignApptMapping, AssignAppointmentMatch, AssignAppointmentRule> {
	public AssignApptMapper(final GipsEngine engine, final Mapping mapping, final AssignAppointmentRule rule) {
		super(engine, mapping, rule);
	}
	
	@Override
	protected AssignApptMapping convertMatch(final String milpVariable, final AssignAppointmentMatch match) {
		return new AssignApptMapping(milpVariable, this.hasBinaryVariable(), match);
	}
}
