/**
 * Generated by org.emoflon.gips.build.generator.templates.PatternMapperTemplate
 */
package audiologyoptimiser.api.gips.mapper;

import audiologyoptimiser.api.AudiologyoptimiserAPI;
import org.emoflon.gips.core.gt.GipsPatternMapper;
import audiologyoptimiser.api.gips.mapping.RoomUsedByStaffMapping;
import org.emoflon.gips.core.GipsEngine;
import audiologyoptimiser.api.rules.StaffRoomDayTuplePattern;
import audiologyoptimiser.api.matches.StaffRoomDayTupleMatch;
import org.emoflon.gips.intermediate.GipsIntermediate.Mapping;

public class RoomUsedByStaffMapper extends GipsPatternMapper<RoomUsedByStaffMapping, StaffRoomDayTupleMatch, StaffRoomDayTuplePattern> {
	public RoomUsedByStaffMapper(final GipsEngine engine, final Mapping mapping, final StaffRoomDayTuplePattern pattern) {
		super(engine, mapping, pattern);
	}
	
	@Override
	protected RoomUsedByStaffMapping convertMatch(final String milpVariable, final StaffRoomDayTupleMatch match) {
		return new RoomUsedByStaffMapping(milpVariable, this.hasBinaryVariable(), match);
	}
}
