/**
 * Generated by org.emoflon.gips.build.generator.templates.MapperFactoryTemplate
 */
package audiologyoptimiser.api.gips;

import audiologyoptimiser.api.gips.mapper.AssignApptMapper;
import audiologyoptimiser.api.AudiologyoptimiserAPI;
import org.emoflon.gips.core.GipsEngine;
import org.emoflon.gips.core.GipsMapper;
import org.emoflon.gips.core.api.GipsMapperFactory;
import org.emoflon.gips.intermediate.GipsIntermediate.Mapping;
import org.emoflon.gips.core.GipsMapping;
import audiologyoptimiser.api.gips.mapper.RoomUsedByStaffMapper;

public class AudiologyoptimiserGipsMapperFactory extends GipsMapperFactory<AudiologyoptimiserAPI> {
	public AudiologyoptimiserGipsMapperFactory(final GipsEngine engine, final AudiologyoptimiserAPI eMoflonApi) {
		super(engine, eMoflonApi);
	}
	
	@Override
	public GipsMapper<? extends GipsMapping> createMapper(final Mapping mapping) {
		switch(mapping.getName()) {
			case "assignAppt" -> {
				return new AssignApptMapper(engine, mapping, eMoflonApi.assignAppointment());
			}
			
			case "roomUsedByStaff" -> {
				return new RoomUsedByStaffMapper(engine, mapping, eMoflonApi.staffRoomDayTuple());
			}
			
			default -> {
				throw new IllegalArgumentException("Unknown mapping type: "+mapping);	
			}
		}
		
	}
}
