/**
 * Generated by org.emoflon.gips.build.generator.templates.TypeExtenderFactoryTemplate
 */
package audiologyoptimiser.api.gips;

import audiologyoptimiser.api.AudiologyoptimiserAPI;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import org.emoflon.gips.core.GipsTypeExtender;
import org.emoflon.gips.core.api.GipsTypeExtenderFactory;
import org.emoflon.gips.intermediate.GipsIntermediate.TypeExtension;

public class AudiologyoptimiserGipsTypeExtensionFactory extends GipsTypeExtenderFactory<AudiologyoptimiserGipsAPI, AudiologyoptimiserAPI> {
	public AudiologyoptimiserGipsTypeExtensionFactory(final AudiologyoptimiserGipsAPI engine, final AudiologyoptimiserAPI eMoflonApi) {
		super(engine, eMoflonApi);
	}

	@Override
	public GipsTypeExtender<?, ?> createTypeExtender(final TypeExtension typeExtension) {
		throw new IllegalArgumentException("Unknown TypeExtension: "+typeExtension);
	}

}
