/**
 * Generated by org.emoflon.gips.build.generator.templates.GipsAPITemplate
 */
package audiologyoptimiser.api.gips;

import audiologyoptimiser.api.gips.mapper.AssignApptMapper;
import audiologyoptimiser.api.AudiologyoptimiserAPI;
import org.eclipse.emf.common.util.URI;
import org.emoflon.gips.core.api.GipsEngineAPI;
import org.emoflon.gips.core.milp.SolverConfig;
import audiologyoptimiser.api.AudiologyoptimiserHiPEApp;
import audiologyoptimiser.api.gips.objective.AudiologyoptimiserGipsObjective;
import org.emoflon.gips.core.milp.Solver;
import org.eclipse.emf.ecore.resource.ResourceSet;
import audiologyoptimiser.api.gips.mapper.RoomUsedByStaffMapper;
import org.emoflon.gips.core.milp.GurobiSolver;
import org.emoflon.gips.core.milp.CplexSolver;
import org.emoflon.gips.core.milp.GlpkSolver;
import org.emoflon.gips.core.GipsObjective;

public class AudiologyoptimiserGipsAPI extends GipsEngineAPI <AudiologyoptimiserHiPEApp, AudiologyoptimiserAPI>{
	final public static URI INTERMEDIATE_MODEL_URI = URI.createFileURI("C:/Users/prapt/audiology_config/audiologyoptimiser/src-gen/audiologyoptimiser/api/gips/gips-model.xmi");
	
	protected AssignApptMapper assignAppt;
	protected RoomUsedByStaffMapper roomUsedByStaff;
	
	public AudiologyoptimiserGipsAPI() {
		super(new AudiologyoptimiserHiPEApp());
	}
	
	/**
	 * Initializes the GIPS engine API with the given model URI.
	 * 
	 * @param modelUri Model URI to load.
	 */
	@Override
	public void init(final URI modelUri) {
		super.initInternal(INTERMEDIATE_MODEL_URI, modelUri);
	}
	
	/**
	 * Initializes the GIPS engine API with the given GIPS intermediate model URI
	 * and the model URI.
	 * 
	 * @param gipsModelURI GIPS intermediate model URI to load.
	 * @param modelUri     Model URI to load.
	 */
	@Override
	public void init(final URI gipsModelURI, final URI modelUri) {
		super.initInternal(gipsModelURI, modelUri);
	}
	
	/**
	 * Initializes the GIPS API with a given GIPS intermediate model URI, a model URI,
	 * and the IBeX pattern path to avoid using hard-coded paths in IBeX
	 * internally.
	 * 
	 * @param gipsModelURI    GIPS intermediate model URI to load.
	 * @param modelUri        Model URI to load.
	 * @param ibexPatternPath IBeX pattern path to load.
	 */
	@Override
	public void init(final URI gipsModelURI, final URI modelUri, final URI ibexPatternPath) {
		super.initInternal(gipsModelURI, modelUri, ibexPatternPath);
	}
	
	/**
	 * Initializes the API with a given resource set as model.
	 * 
	 * @param model Resource set as model.
	 */
	@Override
	public void init(final ResourceSet model) {
		super.initInternal(INTERMEDIATE_MODEL_URI, model);
	}
	
	/**
	 * Initializes the GIPS engine API with the given GIPS intermediate model URI
	 * and a resource set as model.
	 * 
	 * @param gipsModelUri GIPS intermediate model URI to load.
	 * @param model        Resource set as model.
	 */
	@Override
	public void init(final URI gipsModelUri, final ResourceSet model) {
		super.initInternal(gipsModelUri, model);
	}
	
	/**
	    * Initializes the GIPS engine API with the given GIPS intermediate model URI, a
	 * resource set as model, and the IBeX pattern path to avoid using hard-coded
	 * paths in IBeX.
	 * 
	 * @param gipsModelUri    GIPS intermediate model URI to load.
	 * @param model           Resource set as model.
	 * @param ibexPatternPath IBeX pattern path to load.
	 */
	@Override
	public void init(final URI gipsModelUri, final ResourceSet model, final URI ibexPatternPath) {
		super.initInternal(gipsModelUri, model, ibexPatternPath);
	}
	
	public AssignApptMapper getAssignAppt() {
		return assignAppt;
	}
	public RoomUsedByStaffMapper getRoomUsedByStaff() {
		return roomUsedByStaff;
	}
	
	@Override
	protected void createMappers() {
		assignAppt = (AssignApptMapper) mapperFactory.createMapper(name2Mapping.get("assignAppt"));
		addMapper(assignAppt);
		roomUsedByStaff = (RoomUsedByStaffMapper) mapperFactory.createMapper(name2Mapping.get("roomUsedByStaff"));
		addMapper(roomUsedByStaff);
	}
		
	
	@Override
	protected void initMapperFactory() {
		mapperFactory = new AudiologyoptimiserGipsMapperFactory(this, eMoflonAPI);
	}
	
	@Override	
	protected void initConstraintFactory() {
		constraintFactory = new AudiologyoptimiserGipsConstraintFactory(this, eMoflonAPI);
	}
	
	@Override	
	protected void initLinearFunctionFactory() {
		functionFactory = new AudiologyoptimiserGipsLinearFunctionFactory(this, eMoflonAPI);
	}
	
	@Override
	protected void initTypeExtensionFactory() {
		typeExtensionFactory = new AudiologyoptimiserGipsTypeExtensionFactory(this, eMoflonAPI);
	}
	
	@Override
	protected GipsObjective createObjective() {
		return new AudiologyoptimiserGipsObjective(this, gipsModel.getObjective());
	}
	
	@Override
	protected Solver createSolver() {
		Solver solver = null;
		try {
			solver = new GurobiSolver(this, solverConfig);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return solver;
	}
	
	@Override
	protected void updateConstants() {
	}
	
}
