/**
 * Generated by org.emoflon.gips.build.generator.templates.constraint.ConstraintFactoryTemplate
 */
package audiologyoptimiser.api.gips;

import audiologyoptimiser.api.AudiologyoptimiserAPI;
import org.emoflon.gips.intermediate.GipsIntermediate.PatternConstraint;
import org.emoflon.gips.core.GipsEngine;
import audiologyoptimiser.api.gips.constraint.PatternConstraint5OnstaffDayTuple;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import org.emoflon.gips.intermediate.GipsIntermediate.RuleConstraint;
import audiologyoptimiser.api.gips.constraint.PatternConstraint6OnstaffWeekTuple;
import org.emoflon.gips.core.gt.GipsPatternConstraint;
import audiologyoptimiser.api.gips.constraint.PatternConstraint1OnstaffDaySlotTuple;
import org.emoflon.gips.core.GipsMappingConstraint;
import audiologyoptimiser.api.gips.constraint.MappingConstraint3OnroomUsedByStaff;
import org.emoflon.gips.intermediate.GipsIntermediate.MappingConstraint;
import audiologyoptimiser.api.gips.constraint.PatternConstraint2OnroomDaySlotTuple;
import org.emoflon.gips.core.GipsTypeConstraint;
import org.emoflon.gips.core.GipsGlobalConstraint;
import org.emoflon.gips.intermediate.GipsIntermediate.Constraint;
import org.emoflon.gips.core.api.GipsConstraintFactory;
import org.emoflon.gips.intermediate.GipsIntermediate.TypeConstraint;
import audiologyoptimiser.api.gips.constraint.PatternConstraint0OnrequestTuple;
import audiologyoptimiser.api.gips.constraint.MappingConstraint4OnroomUsedByStaff;
import org.emoflon.gips.core.GipsConstraint;

public class AudiologyoptimiserGipsConstraintFactory extends GipsConstraintFactory<AudiologyoptimiserGipsAPI, AudiologyoptimiserAPI> {
	public AudiologyoptimiserGipsConstraintFactory(final AudiologyoptimiserGipsAPI engine, final AudiologyoptimiserAPI eMoflonApi) {
		super(engine, eMoflonApi);
	}
	
	@Override
	public GipsConstraint<AudiologyoptimiserGipsAPI, ? extends Constraint, ? extends Object> createConstraint(final Constraint constraint) {
		switch(constraint.getName()) {
			case "PatternConstraint0OnrequestTuple" -> {
			return new PatternConstraint0OnrequestTuple(engine, (PatternConstraint)constraint, eMoflonApi.requestTuple());
			}
			case "PatternConstraint1OnstaffDaySlotTuple" -> {
			return new PatternConstraint1OnstaffDaySlotTuple(engine, (PatternConstraint)constraint, eMoflonApi.staffDaySlotTuple());
			}
			case "PatternConstraint2OnroomDaySlotTuple" -> {
			return new PatternConstraint2OnroomDaySlotTuple(engine, (PatternConstraint)constraint, eMoflonApi.roomDaySlotTuple());
			}
			case "MappingConstraint3OnroomUsedByStaff" -> {
			return new MappingConstraint3OnroomUsedByStaff(engine, (MappingConstraint)constraint);
			}
			case "MappingConstraint4OnroomUsedByStaff" -> {
			return new MappingConstraint4OnroomUsedByStaff(engine, (MappingConstraint)constraint);
			}
			case "PatternConstraint5OnstaffDayTuple" -> {
			return new PatternConstraint5OnstaffDayTuple(engine, (PatternConstraint)constraint, eMoflonApi.staffDayTuple());
			}
			case "PatternConstraint6OnstaffWeekTuple" -> {
			return new PatternConstraint6OnstaffWeekTuple(engine, (PatternConstraint)constraint, eMoflonApi.staffWeekTuple());
			}
			default -> {
				throw new IllegalArgumentException("Unknown constraint type: "+constraint);	
			}
		}
		
	}
}
