/**
 * Generated by org.emoflon.gips.build.generator.templates.function.FunctionFactoryTemplate
 */
package audiologyoptimiser.api.gips;

import audiologyoptimiser.api.AudiologyoptimiserAPI;
import org.emoflon.gips.intermediate.GipsIntermediate.MappingFunction;
import org.emoflon.gips.core.GipsEngine;
import audiologyoptimiser.api.gips.AudiologyoptimiserGipsAPI;
import org.emoflon.gips.core.GipsMappingLinearFunction;
import org.emoflon.gips.intermediate.GipsIntermediate.LinearFunction;
import org.emoflon.gips.core.api.GipsLinearFunctionFactory;
import audiologyoptimiser.api.gips.objective.DelayCostV2;
import org.emoflon.gips.intermediate.GipsIntermediate.PatternFunction;
import org.emoflon.gips.core.GipsLinearFunction;
import org.emoflon.gips.intermediate.GipsIntermediate.RuleFunction;
import org.emoflon.gips.core.GipsTypeLinearFunction;
import org.emoflon.gips.intermediate.GipsIntermediate.TypeFunction;

public class AudiologyoptimiserGipsLinearFunctionFactory extends GipsLinearFunctionFactory<AudiologyoptimiserGipsAPI, AudiologyoptimiserAPI> {
	public AudiologyoptimiserGipsLinearFunctionFactory(final AudiologyoptimiserGipsAPI engine, final AudiologyoptimiserAPI eMoflonApi) {
		super(engine, eMoflonApi);
	}
	
	@Override
	public GipsLinearFunction<AudiologyoptimiserGipsAPI, ? extends LinearFunction, ? extends Object> createLinearFunction(final LinearFunction function) {
		switch(function.getName()) {
			case "delayCostV2" -> {
				return new DelayCostV2(engine, (MappingFunction)function);
			}
			default -> {
				throw new IllegalArgumentException("Unknown linear function type: " + function);	
			}
		}
		
	}
}
