/**
 * Generated by org.emoflon.gips.build.generator.templates.RuleMappingTemplate
 */
package audiologyoptimiser.api.gips.mapping;

import audiologymodel.Timeslot;
import java.util.Collection;
import audiologymodel.PlanningDay;
import org.emoflon.gips.core.milp.model.RealVariable;
import org.emoflon.gips.core.milp.model.BinaryVariable;
import audiologymodel.StaffMember;
import audiologymodel.PlanningWeek;
import java.util.List;
import org.emoflon.gips.core.milp.model.Variable;
import audiologymodel.AppointmentRequest;
import org.emoflon.gips.core.gt.GipsGTMapping;
import java.util.Map;
import org.emoflon.gips.core.milp.model.IntegerVariable;
import audiologyoptimiser.api.matches.AssignAppointmentMatch;
import audiologymodel.AudiologyBooking;
import audiologyoptimiser.api.rules.AssignAppointmentRule;
import audiologymodel.Room;

public class AssignApptMapping extends GipsGTMapping<AssignAppointmentMatch, AssignAppointmentRule> {
	


	public AssignApptMapping(final String milpVariable, final boolean hasBinaryVariable, final AssignAppointmentMatch match) {
	super(milpVariable, hasBinaryVariable, match);
	

	}

	public AudiologyBooking getBooking() {
		return match.getBooking();
	}
	
	public PlanningDay getPlanningDay() {
		return match.getPlanningDay();
	}
	
	public PlanningWeek getPlanningWeek() {
		return match.getPlanningWeek();
	}
	
	public AppointmentRequest getRequest() {
		return match.getRequest();
	}
	
	public Room getRoom() {
		return match.getRoom();
	}
	
	public StaffMember getStaffMember() {
		return match.getStaffMember();
	}
	
	public Timeslot getStartSlot() {
		return match.getStartSlot();
	}
	

	@Override
	public boolean hasAdditionalVariables() {
	return false;
	}
	
	@Override
	public boolean hasBoundVariables() {
		return false;
	}
	
	@Override
	public boolean hasFreeVariables() {
		return false;
	}
	
	@Override
	public Collection<String> getAdditionalVariableNames() {
		return List.of();
	}
	
	@Override
	public Map<String, Variable<?>> getAdditionalVariables() {
		return Map.of();
	}
	
	@Override
	public Collection<String> getFreeVariableNames() {
		return List.of();
	}
	
	@Override
	public Map<String, Variable<?>> getFreeVariables() {
		return Map.of();
	}
	
	@Override
	public Collection<String> getBoundVariableNames() {
		return List.of();
	}
	
	@Override
	public Map<String, Variable<?>> getBoundVariables() {
		return Map.of();
	}
	
	@Override
	public void setAdditionalVariableValue(final String valName, final double value) {
		throw new UnsupportedOperationException("This mapping <" + name + "> does not have any additonal variables.");
	}
}
